$(document).ready(function(){
	$("#design").click(function(){
		$("#designInfo").show();
		$("#design").hide();
	});
	$("#designInfo").click(function(){
		$("#design").show();
		$("#designInfo").hide();
	});
	$("#development").click(function(){
		$("#developmentInfo").show();
		$("#development").hide();
	});
	$("#developmentInfo").click(function(){
		$("#development").show();
		$("#developmentInfo").hide();
	});
	$("#product").click(function(){
		$("#productInfo").show();
		$("#product").hide();
	});
	$("#productInfo").click(function(){
		$("#product").show();
		$("#productInfo").hide();
	});
});

$(document).ready(function(){
	$("#portfolio1").mouseenter(function(){
		$("#overlay1").show();
	}).mouseleave(function(){
		$("#overlay1").hide();
	});
	$("#portfolio2").mouseenter(function(){
		$("#overlay2").show();
	}).mouseleave(function(){
		$("#overlay2").hide();
	});
	$("#portfolio3").mouseenter(function(){
		$("#overlay3").show();
	}).mouseleave(function(){
		$("#overlay3").hide();
	});
	$("#portfolio4").mouseenter(function(){
		$("#overlay4").show();
	}).mouseleave(function(){
		$("#overlay4").hide();
	});
	$("#portfolio5").mouseenter(function(){
		$("#overlay5").show();
	}).mouseleave(function(){
		$("#overlay5").hide();
	});
	$("#portfolio6").mouseenter(function(){
		$("#overlay6").show();
	}).mouseleave(function(){
		$("#overlay6").hide();
	});
	$("#portfolio7").mouseenter(function(){
		$("#overlay7").show();
	}).mouseleave(function(){
		$("#overlay7").hide();
	});
	$("#portfolio8").mouseenter(function(){
		$("#overlay8").show();
	}).mouseleave(function(){
		$("#overlay8").hide();
	});
})